In [12]:
import pandas as pd

In [13]:
limes=pd.read_csv('Limes.csv')

In [14]:
limes.head()

,Commodity Name,City Name,Type,Package,Variety,Sub Variety,Grade,Date,Low Price,High Price,...,Condition,Appearance,Storage,Crop,Repack,Trans Mode,Offerings,Market Tone,Price Comment,Comments
0,LIMES,ATLANTA,NaN,10 lb cartons,SEEDLESS TYPE,NaN,No Grade Marks,6/27/23,9.0,10.5,...,NaN,NaN,NaN,NaN,N,NaN,NaN,ABOUT STEADY.,NaN,"Wide range in price, condition, and quality."
1,LIMES,ATLANTA,NaN,10 lb cartons,SEEDLESS TYPE,NaN,No Grade Marks,6/27/23,NaN,NaN,...,NaN,FINEAPPEAR,NaN,NaN,N,NaN,NaN,ABOUT STEADY.,one lot 14.25,"Wide range in price, condition, and quality."
2,LIMES,ATLANTA,NaN,10 lb cartons,SEEDLESS TYPE,NaN,No Grade Marks,6/27/23,8.0,9.0,...,NaN,NaN,NaN,NaN,N,NaN,NaN,ABOUT STEADY.,NaN,"Wide range in price, condition, and quality."
3,LIMES,ATLANTA,NaN,10 lb cartons,SEEDLESS TYPE,NaN,No Grade Marks,6/27/23,7.0,8.0,...,NaN,NaN,NaN,NaN,N,NaN,NaN,ABOUT STEADY.,NaN,"Wide range in price, condition, and quality."
4,LIMES,ATLANTA,NaN,40 lb cartons,SEEDLESS TYPE,NaN,No Grade Marks,6/27/23,NaN,NaN,...,NaN,NaN,NaN,NaN,N,NaN,NaN,ABOUT STEADY.,offerings insufficient to quote,"Wide range in price, condition, and quality."

In [15]:
df=pd.read_csv('Limes.csv')

In [16]:
df=pd.read_csv('Limes.csv') 
columns_to_drop = ['Item Size','Origin','Mostly Low','Mostly High','Sub Variety','Grade','Condition', 'Appearance', 'Storage','Crop', 'Repack', 'Trans Mode', 'Offerings', 'Market Tone', 'Price Comment', 'Comments','Origin District','Color','Environment','Unit of Sale','Quality']
df = df.drop(columns=columns_to_drop) # DROP UNWANTED COLUMNS
df = df.dropna(subset=['Package']) # DROP ROWS WITH NULL VALUES IN PACKAGE COLUMN

df['Average Price'] = (df['Low Price'] + df['High Price']) / 2 # FIND THE AVERAGE PRICE USING HIGH AND LOW PRICE
df['Type'] = df['Type'].fillna('Inorganic') #FILL NULL ROWS IN TYPE WITH INORGANIC 
df['Variety'] = df['Variety'].fillna('SEED TYPE') #FILL NULL ROWS IN VARIETY WITH SEED TYPE
df = df.dropna(subset=['Average Price']) # DROP ROWS WITH NULL VALUES IN AVERAGE PRICE 
df

,Commodity Name,City Name,Type,Package,Variety,Date,Low Price,High Price,Average Price
0,LIMES,ATLANTA,Inorganic,10 lb cartons,SEEDLESS TYPE,6/27/23,9.00,10.50,9.750
2,LIMES,ATLANTA,Inorganic,10 lb cartons,SEEDLESS TYPE,6/27/23,8.00,9.00,8.500
3,LIMES,ATLANTA,Inorganic,10 lb cartons,SEEDLESS TYPE,6/27/23,7.00,8.00,7.500
5,LIMES,ATLANTA,Inorganic,40 lb cartons,SEEDLESS TYPE,6/27/23,28.00,30.00,29.000
6,LIMES,ATLANTA,Inorganic,40 lb cartons,SEEDLESS TYPE,6/27/23,23.00,26.00,24.500
...,...,...,...,...,...,...,...,...,...
27199,LIMES,SAN FRANCISCO,Organic,40 lb cartons,SEEDLESS TYPE,3/21/23,48.00,52.00,50.000
27200,LIMES,SAN FRANCISCO,Organic,flats 10 1-lb mesh bags,SEEDLESS TYPE,3/21/23,29.00,30.00,29.500
27201,LIMES,"TORONTO, ONT",Inorganic,10 lb cartons,SEED TYPE,3/21/23,10.98,10.98,10.980
27202,LIMES,"TORONTO, ONT",Inorganic,40 lb cartons,SEED TYPE,3/21/23,62.19,62.19,62.190
27203,LIMES,"TORONTO, ONT",Inorganic,40 lb cartons,SEED TYPE,3/21/23,62.19,65.12,63.655

In [17]:
distinct_values = df['Package'].unique()

# Display the distinct values
distinct_values

array(['10 lb cartons', '40 lb cartons', 'containers 17 2-lb bags',
       'flats 10 1-lb mesh bags', '40 lb containers', '35-36 lb cartons',
       '38 lb cartons', '4 kg containers',
       'reusable plastic cntrs 18 2-lb mesh bags', '15 kg cartons',
       '20 kg cartons', '18 kg cartons', '16 kg cartons',
       '4/5 bushel cartons', 'cartons 18 2-lb bags'], dtype=object)

In [18]:
# NORMALIZE THE PACKAGE COLUMN BY CONVERTING ALL OF THE ROWS TO LB SCALE , CREATE A NEW COLUMN TO STORE THE  VALUES IN LB SCALE 
package_mapping = {
    '10 lb cartons': 10,
    '40 lb cartons': 40,
    'containers 17 2-lb bags': 17 * 2.20462,  # Convert kg to lb
    'flats 10 1-lb mesh bags': 10,
    '40 lb containers': 40,
    '35-36 lb cartons': 36,
    '38 lb cartons': 38,
    '4 kg containers': 4 * 2.20462,  # Convert kg to lb
    'reusable plastic cntrs 18 2-lb mesh bags': 18 * 2.20462,  # Convert kg to lb
    '15 kg cartons': 15 * 2.20462,  # Convert kg to lb
    '20 kg cartons': 20 * 2.20462,  # Convert kg to lb
    '18 kg cartons': 18 * 2.20462,  # Convert kg to lb
    '16 kg cartons': 16 * 2.20462,  # Convert kg to lb
    '4/5 bushel cartons': 5 * 2.20462,  # Convert kg to lb
    'cartons 18 2-lb bags': 18 * 2.20462,  # Convert kg to lb
}

# Map the values in the 'Package' column to numeric values
df['Package Size in pound'] = df['Package'].map(package_mapping)

# Display the preprocessed data
df

,Commodity Name,City Name,Type,Package,Variety,Date,Low Price,High Price,Average Price,Package Size in pound
0,LIMES,ATLANTA,Inorganic,10 lb cartons,SEEDLESS TYPE,6/27/23,9.00,10.50,9.750,10.0
2,LIMES,ATLANTA,Inorganic,10 lb cartons,SEEDLESS TYPE,6/27/23,8.00,9.00,8.500,10.0
3,LIMES,ATLANTA,Inorganic,10 lb cartons,SEEDLESS TYPE,6/27/23,7.00,8.00,7.500,10.0
5,LIMES,ATLANTA,Inorganic,40 lb cartons,SEEDLESS TYPE,6/27/23,28.00,30.00,29.000,40.0
6,LIMES,ATLANTA,Inorganic,40 lb cartons,SEEDLESS TYPE,6/27/23,23.00,26.00,24.500,40.0
...,...,...,...,...,...,...,...,...,...,...
27199,LIMES,SAN FRANCISCO,Organic,40 lb cartons,SEEDLESS TYPE,3/21/23,48.00,52.00,50.000,40.0
27200,LIMES,SAN FRANCISCO,Organic,flats 10 1-lb mesh bags,SEEDLESS TYPE,3/21/23,29.00,30.00,29.500,10.0
27201,LIMES,"TORONTO, ONT",Inorganic,10 lb cartons,SEED TYPE,3/21/23,10.98,10.98,10.980,10.0
27202,LIMES,"TORONTO, ONT",Inorganic,40 lb cartons,SEED TYPE,3/21/23,62.19,62.19,62.190,40.0
27203,LIMES,"TORONTO, ONT",Inorganic,40 lb cartons,SEED TYPE,3/21/23,62.19,65.12,63.655,40.0

In [19]:
df.count()

Commodity Name           24894
City Name                24894
Type                     24894
Package                  24894
Variety                  24894
Date                     24894
Low Price                24894
High Price               24894
Average Price            24894
Package Size in pound    24894
dtype: int64

In [20]:
df['Price per Pound'] = df['Average Price'] / df['Package Size in pound']

In [21]:
df

,Commodity Name,City Name,Type,Package,Variety,Date,Low Price,High Price,Average Price,Package Size in pound,Price per Pound
0,LIMES,ATLANTA,Inorganic,10 lb cartons,SEEDLESS TYPE,6/27/23,9.00,10.50,9.750,10.0,0.975000
2,LIMES,ATLANTA,Inorganic,10 lb cartons,SEEDLESS TYPE,6/27/23,8.00,9.00,8.500,10.0,0.850000
3,LIMES,ATLANTA,Inorganic,10 lb cartons,SEEDLESS TYPE,6/27/23,7.00,8.00,7.500,10.0,0.750000
5,LIMES,ATLANTA,Inorganic,40 lb cartons,SEEDLESS TYPE,6/27/23,28.00,30.00,29.000,40.0,0.725000
6,LIMES,ATLANTA,Inorganic,40 lb cartons,SEEDLESS TYPE,6/27/23,23.00,26.00,24.500,40.0,0.612500
...,...,...,...,...,...,...,...,...,...,...,...
27199,LIMES,SAN FRANCISCO,Organic,40 lb cartons,SEEDLESS TYPE,3/21/23,48.00,52.00,50.000,40.0,1.250000
27200,LIMES,SAN FRANCISCO,Organic,flats 10 1-lb mesh bags,SEEDLESS TYPE,3/21/23,29.00,30.00,29.500,10.0,2.950000
27201,LIMES,"TORONTO, ONT",Inorganic,10 lb cartons,SEED TYPE,3/21/23,10.98,10.98,10.980,10.0,1.098000
27202,LIMES,"TORONTO, ONT",Inorganic,40 lb cartons,SEED TYPE,3/21/23,62.19,62.19,62.190,40.0,1.554750
27203,LIMES,"TORONTO, ONT",Inorganic,40 lb cartons,SEED TYPE,3/21/23,62.19,65.12,63.655,40.0,1.591375